version: '3.8'

services:

  banco-postgress:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "test"
    volumes:
        - ./DataBase:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    mem_limit: 500m

  node-app:
    container_name: back
    build: './backend/'
    command:
        yarn start
    volumes:
        - /usr/app
    ports:
        - "3333:3333"
    networks:
        - postgres-compose-network
    depends_on:
        - banco-postgress
    mem_limit: 500m
  web:
    container_name: front
    build: angular
    ports:
      - "4200:4200"
    depends_on:
        - node-app
        - banco-postgress
    networks:
        - postgres-compose-network
networks:
   postgres-compose-network:
    driver: bridge

